version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/internal/tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
