builds:
  - id: stanza
    binary: stanza_{{ .Os }}_{{ .Arch }}
    main: ./cmd/stanza
    env:
      - CGO_ENABLED=0
    flags: -tags=timetzdata
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -X github.com/observiq/stanza/version.GitTag={{ .Tag }}
      - -X github.com/observiq/stanza/version.GitCommit={{ .FullCommit }}
    no_unique_dist_dir: true
    hooks:
      post: ./build/post.sh

archives:
  - builds:
      - stanza
    # skip archiving as tar.gz / zip
    format: binary

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-SHA256SUMS"
  algorithm: sha256

release:
  github:
    owner: observIQ
    name: stanza
  extra_files:
  - glob: scripts/*install*
  - glob: stanza*.msi

changelog:
  skip: false
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999

dist: artifacts
