# This example configuration uses two plugins that are defined
# in the ./plugins directory. See those files for details
pipeline:
  # repeater is a plugin defined by ./plugins/repeater.yaml
  - type: repeater

  # decorator is a plugin defined by ./plugins/decorator.yaml
  # It adds the label "decorated" to each entry that passes through
  # it with the value specified here
  - type: decorator
    value: my_decorated_value

  - type: stdout
