// Code generated by mockery v1.0.0. DO NOT EDIT.

package testutil

import mock "github.com/stretchr/testify/mock"
import plugin "github.com/bluemedora/bplogagent/plugin"

// Outputter is an autogenerated mock type for the Outputter type
type Outputter struct {
	mock.Mock
}

// ID provides a mock function with given fields:
func (_m *Outputter) ID() plugin.PluginID {
	ret := _m.Called()

	var r0 plugin.PluginID
	if rf, ok := ret.Get(0).(func() plugin.PluginID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(plugin.PluginID)
	}

	return r0
}

// Outputs provides a mock function with given fields:
func (_m *Outputter) Outputs() []plugin.Inputter {
	ret := _m.Called()

	var r0 []plugin.Inputter
	if rf, ok := ret.Get(0).(func() []plugin.Inputter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plugin.Inputter)
		}
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *Outputter) Type() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
