// Code generated by mockery v1.0.0. DO NOT EDIT.

package testutil

import mock "github.com/stretchr/testify/mock"
import plugin "github.com/bluemedora/bplogagent/plugin"

// PluginConfig is an autogenerated mock type for the PluginConfig type
type PluginConfig struct {
	mock.Mock
}

// Build provides a mock function with given fields: _a0
func (_m *PluginConfig) Build(_a0 plugin.BuildContext) (plugin.Plugin, error) {
	ret := _m.Called(_a0)

	var r0 plugin.Plugin
	if rf, ok := ret.Get(0).(func(plugin.BuildContext) plugin.Plugin); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.Plugin)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(plugin.BuildContext) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ID provides a mock function with given fields:
func (_m *PluginConfig) ID() plugin.PluginID {
	ret := _m.Called()

	var r0 plugin.PluginID
	if rf, ok := ret.Get(0).(func() plugin.PluginID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(plugin.PluginID)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *PluginConfig) Type() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
