// Code generated by mockery v1.0.0. DO NOT EDIT.

package testutil

import mock "github.com/stretchr/testify/mock"
import plugin "github.com/bluemedora/bplogagent/plugin"

// Plugin is an autogenerated mock type for the Plugin type
type Plugin struct {
	mock.Mock
}

// ID provides a mock function with given fields:
func (_m *Plugin) ID() plugin.PluginID {
	ret := _m.Called()

	var r0 plugin.PluginID
	if rf, ok := ret.Get(0).(func() plugin.PluginID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(plugin.PluginID)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *Plugin) Type() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
