---
pipeline:

  # Read lines from Apache Tomcat access logs
  # Example input line:
  # 10.66.2.46 - - [13/Mar/2019:10:43:00 -0400] "GET / HTTP/1.1" 404 -
  - type: file_input
    start_at: beginning
    include:
      - ./access.log
    labels:
      log_type: tomcat

  # Parse the logs into labeled fields
  # Example input:
  # {
  #   "timestamp": "2020-06-13T11:00:53-04:00",
  #   "record": "10.66.2.46 - - [13/Mar/2019:10:43:00 -0400] "GET / HTTP/1.1" 404 -"
  # }
  - type: regex_parser
    regex: >-
      (?P<remote_host>[^\s]+)
      -
      (?P<remote_user>[^\s]+)
      \[(?P<timestamp>[^\]]+)\]
      "(?P<http_method>[A-Z]+)
      (?P<url_path>[^\s]+)[^"]*"
      (?P<http_status>\d+)
      (?P<bytes_sent>[\d-]+)
    timestamp:
      parse_from: timestamp
      layout: '%d/%b/%Y:%H:%M:%S %z'
    severity:
      parse_from: http_status
      preserve_to: http_status
      mapping:
        error: "4xx"
        info:
          - min: 300
            max: 399
        debug: 200

  # Write the log to stdout
  # Example input:
  # {
  #   "timestamp": "2019-03-13T11:00:53-04:00",
  #   "severity": 60,
  #   "record": {
  #     "bytes_sent": "19698",
  #     "http_method": "GET",
  #     "http_status": "200",
  #     "remote_host": "10.66.2.46",
  #     "remote_user": "-",
  #     "url_path": "/manager/images/asf-logo.svg"
  #   }
  # }
  - type: stdout
