---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: stanza-metadata
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stanza-metadata
  namespace: default
rules:
  - apiGroups: ["", "apps", "batch"]
    resources:
      - pods
      - namespaces
      - replicasets
      - jobs
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stanza-metadata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stanza-metadata
subjects:
  - kind: ServiceAccount
    name: stanza-metadata
    namespace: default
---
kind: ConfigMap
metadata:
  name: stanza-config
  namespace: default
apiVersion: v1
data:
  config.yaml: |2-
    pipeline:
      - type: kubernetes_container
        cluster_name: stanza_gke
        # avoid parsing stanza's log output
        exclude:
          - /var/log/containers/stanza-*_*-*.log
        start_at: end

      # https://github.com/observIQ/stanza/blob/master/docs/operators/google_cloud_output.md
      # When Stanza is running on GKE, a project_id and credentials_file parameters are not required when
      # the node pool as the "logging" scope enabled
      - type: google_cloud_output
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: stanza
  namespace: default
spec:
  selector:
    matchLabels:
      name: stanza
  template:
    metadata:
      labels:
        name: stanza
    spec:
      serviceAccountName: stanza-metadata
      containers:
        - name: stanza
          # Production deployments should use an image tag other than latest
          image: observiq/stanza:latest
          imagePullPolicy: Always
          # Override args in order to set database location
          # to the database hostPath volume
          args:
            - --config
            - /stanza_home/config.yaml
            - --database
            - /stanza_home/database/stanza.db
            - --plugin_dir
            - /stanza_home/plugins
          resources:
            # keeping limit and request the same gives stanza
            # a higher QoS
            limits:
              memory: "500Mi"
              cpu: 500m
            requests:
              memory: "500Mi"
              cpu: 500m
          volumeMounts:
            - mountPath: /stanza_home/config.yaml
              name: config
              subPath: config.yaml
            - mountPath: /var/log
              name: varlog
            - mountPath: /stanza_home/database/
              name: database
              readOnly: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: stanza-config
        - name: database
          hostPath:
            path: /var/observiq-agent/database
