package testutil

// This is NOT generated by mockery as the interface we are mocking is in the opentelemetry-log-collection/operator package

import (
	context "context"

	"github.com/open-telemetry/opentelemetry-log-collection/operator"
	"github.com/stretchr/testify/mock"
)

var _ (operator.Persister) = (*MockPersister)(nil)

type MockPersister struct {
	mock.Mock
}

func (m *MockPersister) Get(ctx context.Context, key string) ([]byte, error) {
	args := m.Called(ctx, key)

	if args.Get(0) == nil {
		return nil, args.Error(1)
	}

	return args.Get(0).([]byte), args.Error(1)
}

func (m *MockPersister) Set(ctx context.Context, key string, value []byte) error {
	args := m.Called(ctx, key, value)
	return args.Error(0)
}

func (m *MockPersister) Delete(ctx context.Context, key string) error {
	args := m.Called(ctx, key)
	return args.Error(0)
}
