package main

import (
	// Load packages when importing input operators
	_ "github.com/observiq/stanza/v2/operator/builtin/input/aws/cloudwatch"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/azure/eventhub"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/azure/loganalytics"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/file"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/forward"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/generate"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/goflow"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/http"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/k8sevent"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/stanza"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/stdin"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/tcp"
	_ "github.com/observiq/stanza/v2/operator/builtin/input/udp"

	_ "github.com/observiq/stanza/v2/operator/builtin/parser/csv"
	_ "github.com/observiq/stanza/v2/operator/builtin/parser/json"
	_ "github.com/observiq/stanza/v2/operator/builtin/parser/keyvalue"
	_ "github.com/observiq/stanza/v2/operator/builtin/parser/regex"
	_ "github.com/observiq/stanza/v2/operator/builtin/parser/severity"
	_ "github.com/observiq/stanza/v2/operator/builtin/parser/syslog"
	_ "github.com/observiq/stanza/v2/operator/builtin/parser/time"
	_ "github.com/observiq/stanza/v2/operator/builtin/parser/uri"
	_ "github.com/observiq/stanza/v2/operator/builtin/parser/xml"

	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/add"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/copy"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/filter"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/flatten"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/hostmetadata"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/k8smetadata"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/metadata"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/move"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/noop"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/ratelimit"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/recombine"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/remove"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/restructure"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/retain"
	_ "github.com/observiq/stanza/v2/operator/builtin/transformer/router"

	_ "github.com/observiq/stanza/v2/operator/builtin/output/drop"
	_ "github.com/observiq/stanza/v2/operator/builtin/output/elastic"
	_ "github.com/observiq/stanza/v2/operator/builtin/output/file"
	_ "github.com/observiq/stanza/v2/operator/builtin/output/forward"
	_ "github.com/observiq/stanza/v2/operator/builtin/output/googlecloud"
	_ "github.com/observiq/stanza/v2/operator/builtin/output/newrelic"
	_ "github.com/observiq/stanza/v2/operator/builtin/output/stdout"
)
