# WindowsMSI is responsible for building and testing a Windows MSI package.
name: WindowsMSI
on:
  pull_request:

jobs:
  build_msi:
    runs-on: windows-2019
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
        
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
          check-latest: true
      
      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: |
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Build Windows Binary
        run: |
          make build-windows
          artifacts/stanza_windows_amd64 build/windows/stanza.exe

      - name: Get Latest stanza-plugins Release
        id: pluginsrelease
        run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/observiq/stanza-plugins/releases/latest | jq '.tag_name' | tr -d '"')"

      - name: Clone and Checkout Latest Plugins
        uses: actions/checkout@master
        with:
          name: observiq/stanza-plugins
          ref: ${{ steps.pluginsrelease.outputs.releasetag }}
          path: stanza-plugins

      - name: Copy Plugins to MSI Build Directory
        run: cp -r stanza-plugins/plugins build/windows/

      # Installs go-msi, wix, and cinc to C:/. The system PATH is updated to include this directory.
      - name: Install Build and Test Tools
        run: 	|
          curl -L -o go-msi.exe https://github.com/observIQ/go-msi/releases/download/v2.0.0/go-msi.exe
          curl -L -o wix310-binaries.zip http://wixtoolset.org/downloads/v3.10.3.3007/wix310-binaries.zip
          unzip wix310-binaries.zip
          curl -L -o cinc-auditor.msi http://downloads.cinc.sh/files/stable/cinc-auditor/4.17.7/windows/2012r2/cinc-auditor-4.17.7-1-x64.msi
          echo "C:\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        working-directory: C:/

      # TODO(jsirianni): Get tag dynamic
      - name: Build MSI
        run: go-msi.exe make -m stanza-v0.0.1.msi --version v0.0.1 --arch amd64
        working-directory: build/windows/

      # TODO(jsirianni): Get tag dynamic
      - name: Install MSI
        run: stanza-v0.0.1.msi
        working-directory: build/windows/

      - name: Run CINC (Inspec) Tests
        run: cinc-auditor exec inspec.rb
        working-directory: build/windows/test